name: Run API Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run TestNG Suite with Maven
      run: mvn clean test

    - name: Upload TestNG Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-results
        path: target/surefire-reports/